version: '3.8'
services:
  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
      PGPORT: 5434
    ports:
      - "5434:5434"
    expose:
      - 5434
    volumes:
      - ./db:/var/lib/postgresql/data
  api:
    build: .
    depends_on:
      - db
    ports:
      - "8080:8080"
    volumes:
      - .:/app
    extra_hosts:
      - "host.docker.internal:172.17.0.1"
volumes:
  db:


